version: '3'
services:
  app:
    build: .
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.develop
    tty: true
